### ISSUE TITLE
 Compile error

### ISSUE THREAD

**Issue by Andrespzgz** [Fabien-Chouteau/ACNC#1]
I have a problem compiling the project. in the photo I show you what appears to me and I can not find that file.
![acnc](https://user-images.githubusercontent.com/32250858/30814178-0ca9bc28-a1d5-11e7-9d07-ea6912cea42e.jpg)

**Comment by Fabien-Chouteau** [comment]
Hi @Andrespzgz 

The project was not compatible with GNAT GPL 2017, I fixed it now.

Please update the project and the submodules and let me know if it continues to fail.

Regards,

**Comment by Andrespzgz** [comment]
Actually the problem was because of the software update, no pence in rehearsing with an earlier version, thank you so much for your timely and timely response. What a shame to bother you with the issue of connection board with GNAT-GPL, but I have a STM31f407VG and the code is for the STM32F4xx series, and the drawback is the connection to download the firmware, do not know if you have any solution and install the driver and I still have the problem, I am also looking at how to solve this small problem.

regards!
![acnc_conection](https://user-images.githubusercontent.com/32250858/30931574-ade8c8b6-a38a-11e7-8696-048bb1950c90.jpg)

**Comment by Andrespzgz** [comment]
Hi @Fabien-Chouteau 

Actually the problem was because of the software update, no pence in rehearsing with an earlier version, thank you so much for your timely and timely response. What a shame to bother you with the issue of connection board with GNAT-GPL, but I have a STM31f407VG and the code is for the STM32F4xx series, and the drawback is the connection to download the firmware, do not know if you have any solution and install the driver and I still have the problem, I am also looking at how to solve this small problem.

regards!
![acnc_conection](https://user-images.githubusercontent.com/32250858/30931619-d04f2986-a38a-11e7-9d67-ea045eefec7b.jpg)

**Comment by Andrespzgz** [comment]
thank you very much :) and I compose without any problem.
