### ISSUE TITLE
Connect with the board

### ISSUE THREAD

**Issue by Andrespzgz** [Fabien-Chouteau/ACNC#3]
![acnc_conection](https://user-images.githubusercontent.com/32250858/30994364-3d0a71c2-a479-11e7-9d06-cea8e646b7b4.jpg)
Hi @ Fabien-Chouteau

Sorry to bother again, but you solved the error I had for the update of GNAT, now I can not download the software to the board, but I have already downloaded the driver of the STM32F407VG and install it so GNAT-GPL can recognize it and can download the software. But I really can not solve this inconvenience, I greatly appreciate it if you can give me some idea.

Thank you very much for your kind attention. regards!

**Comment by Fabien-Chouteau** [comment]
Hello @Andrespzgz 

As stated in the error message, you have to specify the connection tool.

There are examples in this blog post : http://blog.adacore.com/gps-for-bare-metal-development

Regards,

**Comment by Andrespzgz** [comment]
Yes, I just did not find any information about it. Thank you very much for your time, I will review the information you send me.
