### ISSUE TITLE
Thanks for your help ! 

### ISSUE THREAD

**Issue by Andrespzgz** [Fabien-Chouteau/ACNC#4]
Hi, Fabien,

Thank you very much for your help. finally manage to compile the firmware to perfection and upload it to the card :)

**Comment by Andrespzgz** [comment]
Hi, Fabien,

Thank you very much for your help. finally manage to compile the firmware to perfection and upload it to the card :)

**Comment by Fabien-Chouteau** [comment]
That's nice to hear. 

Thanks for the update,
