### ISSUE TITLE
Firmware Operation

### ISSUE THREAD

**Issue by Andrespzgz** [Fabien-Chouteau/ACNC#5]
Hi, Fabien,
I have a question, I sent the code G but there is no action on the pins that you stated both for the direction and the steps in the motors.

Thank you very much.

**Comment by Fabien-Chouteau** [comment]
Hi @Andrespzgz,

Sorry for the late answer. I can't help you with so little information, you should connect a debugger and see if the characters are received by the UART driver.

Best regards,
